feat: add support for GitLab CI
pipelinit/pipelinit-cli pull request #111
Opened 2021-12-16 19:48 UTC by joao10lima

- Unlock GitLab CI as a platform in Pipelinit.
- Add the Python stack for GitLab CI

Pipelinit generates a main `.gitlab-ci.yml` and in this file
is declared the stages for the stack. Inside the folder `.gitlab-ci`
is created the files with the scrips and necessary images.

https://github.com/pipelinit/pipelinit-cli/issues/54

To test:
- `deno test --unstable --allow-all`
- Test on a Python project in GitLab

Examples:
- https://gitlab.com/joao10lima/pipelinit-sample-python
- https://gitlab.com/joao10lima/pipelinit-sample-python/-/pipelines/431335910

![image](https://user-images.githubusercontent.com/30262244/146438438-82130713-fc0d-4319-934a-f4168218c0e5.png)
![image](https://user-images.githubusercontent.com/30262244/146438546-dbe2f525-f544-4801-9e62-e60700cef3ce.png)
![image](https://user-images.githubusercontent.com/30262244/146438635-62bbafb2-3b55-4511-a47c-f290e3f600b3.png)

2021-12-28 14:00 UTC, oesgalha requested changes
Well done!! 👏 👏 

Can you rebase to fix the README conflict and update the file headers version (pipelinit 0.3.0 instead of 0.2.2)?

I've also included a couple of notes about the generated files, can you take a look?

2021-12-29 19:11 UTC, joao10lima commented on core/templates/gitlab/python/.gitlab-ci.yml
> +      - "**/*.py"
Nice, I managed to test it here:
https://gitlab.com/joao10lima/pipelinit-sample-python/-/pipelines/438684483
![image](https://user-images.githubusercontent.com/30262244/147695685-b855b2e8-6a84-423c-b142-3260cabf1118.png)

It works just fine!

2021-12-30 12:28 UTC, oesgalha requested changes
Great! 😁 

There is one last detail in the Python templates:

2021-12-30 12:28 UTC, oesgalha commented on core/templates/gitlab/python/format.yaml
> +  image: python:3.6.10
Use the discovered Python version (`it.version`) instead of a fixed one

2021-12-30 14:55 UTC, merged