Feat/GitHub starter stacks
pipelinit/pipelinit-cli pull request #27
Opened 2021-09-08 12:44 UTC by joao10lima

As described in the issue #23, using as example the GitHub starters CI, add to the pipelinit the following stacks:
- Docker stack
  - Lint stage
  - Build stage
- Complement python stack
  - Django and PyTest
  - Black as formatter and flake8 adjusted
- Complement JavaScript stack
  - Add a stage test

To test:

2021-09-09 20:12 UTC, oesgalha requested changes
Thank you!

I've made some suggestions below, can you take a look?

---

In the README file, Increase the rowspan from the cells with "Coming soon" from 8 to 13. This will make the last columns render with all the rows.

2021-09-09 20:12 UTC, oesgalha commented on core/plugins/stack/python/django.ts
> +  return false;
Use the `includes` helper to do this: 
```suggestion
  return await context.files.includes("**/manage.py");
```

2021-09-09 20:12 UTC, oesgalha commented on core/templates/github/javascript/test.yaml
> +      - run: <%= it.packageManager.name %> ci
This should be `npm ci` for npm or `yarn` for yarn.

2021-09-09 20:12 UTC, oesgalha commented on core/templates/github/python/lint.yaml
> +      - run: flake8 --ignore E203,E501,W503 .
Can you add a comment here explaining why those should be ignored?

2021-09-10 13:55 UTC, joao10lima commented
> Thank you!
> 
> I've made some suggestions below, can you take a look?
> 
> In the README file, Increase the rowspan from the cells with "Coming soon" from 8 to 13. This will make the last columns render with all the rows.

Thanks for the comments, I've changed accordingly and updated the README example section text

2021-09-13 12:45 UTC, oesgalha approved these changes

2021-09-13 12:46 UTC, merged